[package]
name = "bottleneck"
version = "0.3.0"
authors = ["Dynisious <daniel.bechaz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sync-stack = { version = "0.1", features = ["std"] }
